package util;

/**
 * Class which contains the explanations for the
 * different steps in our program execution.
 * 
 * @author	Camacho Sosa, José Manuel
 * @author	Muñoz Ríos, Gabriel
 * @author	Pozo Nuñez, José Antonio
 * @version	1.0, 10 Jan 2013
 */
public class Strings {

	/**
	 * Static method to get the explanation by the
	 * index of the step.
	 * 
	 * @param	index	index of the step
	 * @return			a string which contains the
	 * 					appropriate explanation
	 */
	public static String getExplanation(int index) {
		String result = "";

		if(index == 0) {
			result = "As a first step we use a filter to remove noise, called remove " +
					"outliers. The noise in the image is text or lines that are not part of " +
					"the watermark or background. This filter replaces each pixel from the " +
					"median of an established radius only if that pixel distinguishes more " +
					"that a certain threshold value. Furthermore, the pixel only gets modified " +
					"if it is a dark pixel.";
		} else if(index == 1) {
			result = "For the next step we need to subract the image background. To do this we " +
					"apply the algorithm of the rolling ball. In this algorithm the image has " +
					"a third dimension, where the height are the values ​​of the image and this" +
					"creates a surface. With a ball of a certain radius, we cross the bottom" +
					"surface and adjust the values ​​of the image which those places that the " +
					"ball can pass.";
		} else if(index == 2) {
			result = "In the next step we need to isolate the watermark and we'll do it with " +
					"simple arithmetic subtraction. For that we will cross the images of the " +
					"two steps above and subtract each pixel with its appropriate in the " +
					"other image.";
		} else if(index == 3) {
			result = "From this image in the next step we need to highlight the watermark. " +
					"We will use a Sobel filter, where two masks will calculate an " +
					"approximation of the gradient of each pixel using convolution.";
		} else if(index == 4) {
			result = "The next step is a simple binarization for obtain the watermark in a " +
					"white background. The only strange aspect is that the choice of the " +
					"threshold is automatic. Uses an algorithm that selects a threshold " +
					"associated with the composite average of the pixel values​​.";
		} else if(index == 5){
			result = "In the next step we need to remove the noise generated by faults in " +
					"the paper so we will use a median filter. This filter replaces each " +
					"pixel by the median in an established radius.";
		} else {
			result = "This is the final result.";
		}
		
		return result;
	}
	
}
